In [63]:
from sklearn.linear_model import LogisticRegression
import pandas as pd
import numpy as np

In [95]:
X = np.array([[-5], [1], [2], [3]])
y = np.array([0, 0, 0, 1])

In [96]:
lr = LogisticRegression()
lr.fit(X, y)

LogisticRegression()

In [97]:
y_pred = lr.predict(X)
print(y_pred)

[0 0 0 0]


In [98]:
lr.score(X, y)

0.75

In [99]:
lr.decision_function(X)

array([-5.77785386, -1.47254015, -0.75498787, -0.03743558])

In [100]:
lr.predict_proba(X)

array([[0.9969142 , 0.0030858 ],
       [0.81344317, 0.18655683],
       [0.68026456, 0.31973544],
       [0.5093578 , 0.4906422 ]])

In [101]:
from sklearn.metrics import confusion_matrix

In [102]:
conf_mat = confusion_matrix(y,y_pred)
conf_mat

array([[3, 0],
       [1, 0]], dtype=int64)